data_name: CIFAR10

num_arm: 10
dim_context: 3072
T: 25000

algo: NeuralUCB
model: neural
act: ReLU
loss: L2
batchsize: 128
num_iter: 50
lr: 0.01
reg: 0.01
nu: 0.001

project: ContextualBandit-Image
group: Cifar10-neuralUCB