data_name: CIFAR10

num_arm: 10
dim_context: 3072
T: 25000

algo: LinTS
model: neural
act: ReLU
loss: L2
batchsize: 128
num_iter: 50
beta_inv: 0.00001
lr: 0.01
reg: 0.01

project: ContextualBandit-Image
group: Cifar10-LMCTS