datapath: data/gaussian50-20-1-1.pt

num_arm: 50
dim_context: 20
T: 10000
sigma: 1.0
func: quad

algo: NeuralUCB
model: neural
layers: [20, 20, 20]
act: ReLU
num_iter: 100
nu: 0.01
reg: 0.001
lr: 0.01

project: ContextualBandit-Neurips
group: Quad-NeuralUCB