datapath: data/gaussian50-20-1-1.pt
num_arm: 50
dim_context: 20
T: 10000
sigma: 1.0
func: quad

algo: NeuralEpsGreedy
model: neural
layers: [20, 20, 20]
act: ReLU
num_iter: 100
lr: 0.01
eps: 0.01

project: ContextualBandit-Neurips
group: Quad-NeuralEpsGreedy