data_name: adult
version: 2
num_data: 20000

num_arm: 2
dim_context: 14
T: 10000

algo: NeuralTS
model: neural
act: ReLU
layers: [100]
loss: L2
num_iter: 100
reg: 0.01
nu: 0.000001
lr: 0.01

project: ContextualBandit-Neurips
group: Adult-NeuralTS