data_name: covertype
version: 3
num_data: 15000

num_arm: 7
dim_context: 54
T: 15000

algo: FGNeuralTS
model: neural
act: ReLU
layers: [100]
loss: L2
num_iter: 100
lr: 0.01
reg: 0.001
nu: 0.01

feel_good: true
fg_mode: "hard"
lambda_fg: 1.0
b_fg: 1.0
smooth_s: 10.0

project: ContextualBandit-UCI
group: Covertype-FGNeuralTS 