data_name: financial
version: 1
num_data: 100  # Number of time points to use

# bandit
num_arm: 10    # Number of assets
dim_context: 20  # Feature dimension for each asset
T: 10000       # Number of rounds

# train
algo: LMCTS
model: neural
act: LeakyReLU
layers: [100, 50, 25]  # Enhanced architecture: wider first layer, narrowing down
num_iter: 100  # More update iterations per step
beta_inv: 0.001  # 10x higher to increase exploration
lr: 0.01

# log
project: ContextualBandit-Financial
