data_name: mushroom
version: 1
num_data: 8000

num_arm: 2
dim_context: 22
T: 10000

algo: FGNeuralTS
model: neural
act: ReLU
layers: [100]
loss: L2
num_iter: 100
lr: 0.01
reg: 0.00001
nu: 0.00001

feel_good: true
fg_mode: "hard"
lambda_fg: 1.0
b_fg: 1.0
smooth_s: 10.0

project: ContextualBandit-Neurips
group: Mushroom-FGNeuralTS 