_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.9
            "8":
                - 5
            "10":
                - 20
            "12": 0.19.9
            "13": linux-x86_64
"N":
    value: 1
T:
    value: 10000
agent:
    value: src.baseline.EpsGreedy
context_size:
    value: 4
d:
    value: 20
epsilon:
    value: 0.01
exp_name:
    value: results/toy/epsgreedy/
game:
    value: src.game.GameToy
nb_arms:
    value: 5
out_dir:
    value: /home/sarahl/PLMC-TS/linear_results_5
phi:
    value: __main__.load_config_file.<locals>.<lambda>
phi_a:
    value: __main__.load_config_file.<locals>.<lambda>
project_name:
    value: Lin_EpsGreedy
std_reward:
    value: 0.5
task_type:
    value: linear
